version: '3.9'

services:
  php:
    networks:
      - phplogger
    container_name: php
    ports:
      - "9001:9000"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/phplogger

networks:
  phplogger:

